apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecom-backend
  labels:
    app: ecom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecom
  template:
    metadata:
      labels:
        app: ecom
    spec:
      containers:
        - name: ecom
          image: myregistry/devsecops-ai-ecom:latest   # images with :latest flagged by policies
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          securityContext:
            privileged: true    # kyverno/opa will flag
            runAsUser: 0        # running as root -> violation
          volumeMounts:
            - name: host-volume
              mountPath: /host   # hostPath mount -> flagged
      volumes:
        - name: host-volume
          hostPath:
            path: /var/lib
