name: DevSecOps Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  gitleaks:
    name: Gitleaks Secret Scan
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Get gitleaks docker image
        run: docker pull ghcr.io/gitleaks/gitleaks:latest

      - name: Run Gitleaks
        run: docker run -v $(pwd):/path ghcr.io/gitleaks/gitleaks:latest detect --source /path --report-format sarif --report-path /path/gitleaks.sarif --no-git --exit-code 0
      
      - name: Upload Gitleaks SARIF to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: gitleaks.sarif

      - name: Archive report
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-report
          path: gitleaks.sarif

  semgrep:
    name: Semgrep SAST
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep
        run: semgrep --config auto --output semgrep.sarif --sarif .

      - name: Upload Semgrep SARIF to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif

      - name: Archive report
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-report
          path: semgrep.sarif

  trivy:
    name: Trivy Image Scan
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t insecure-ecom:latest .

      - name: Run Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "image"
          image-ref: "insecure-ecom:latest"
          format: "sarif"
          output: "trivy.sarif"
          ignore-unfixed: true
          severity: 'CRITICAL'
          exit-code: "0"

      - name: Upload SARIF to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy.sarif

      - name: Archive report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy.sarif

  checkov:
    name: Checkov IaC Scan
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Install Checkov
        run: pip install checkov

      - name: Run Checkov Scan
        run: |
          checkov -d terraform \
            --framework terraform \
            --output sarif \
            --soft-fail

      - name: Archive report
        uses: actions/upload-artifact@v4
        with:
          name: checkov-report
          path: results.sarif

      Checkov's SARIF is invalid. Uncomment when we have a way to upload SARIF to GitHub.
      - name: Upload Checkov SARIF to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: checkov.sarif
